apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jetstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.17.0
    helm:
      valuesObject:
        crds:
          enabled: true
  project: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

