apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cattle-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.10.2
    helm:
      valuesObject:
        hostname: rancher.172.23.97.75.sslip.io
        bootstrapPassword: bootstrapPassword
        replicas: 1
  project: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

