apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reporef
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-workdir
  resources:
    requests:
      storage: 5Gi
